services:
  efex-backend:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file: backend/.env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  efex-frontend:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    command: pnpm dev --host --port 3000
    volumes:
      - ./frontend:/app